name: Build and Deploy Ionic App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Instalar dependencias
        run: npm ci

      - name: 4. Compilar la aplicación Ionic
        run: npx ng build --configuration production --base-href /proyectonacho/

      - name: 5. Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/app/browser
          branch: gh-pages